# Generated by Django 3.0.5 on 2020-06-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
